// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MakeAsReadUnreadController from "./make_as_read_unread_controller"
application.register("make-as-read-unread", MakeAsReadUnreadController)

import SearchController from "./search_controller"
application.register("search", SearchController)
